// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: apci/users/v1/users.proto

package usersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Ed25519PublicKey []byte                 `protobuf:"bytes,2,opt,name=ed25519_public_key,json=ed25519PublicKey,proto3" json:"ed25519_public_key,omitempty"`
	DeviceHash       string                 `protobuf:"bytes,3,opt,name=device_hash,json=deviceHash,proto3" json:"device_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_apci_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_apci_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEd25519PublicKey() []byte {
	if x != nil {
		return x.Ed25519PublicKey
	}
	return nil
}

func (x *RegisterRequest) GetDeviceHash() string {
	if x != nil {
		return x.DeviceHash
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_apci_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_apci_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BeginLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginLoginRequest) Reset() {
	*x = BeginLoginRequest{}
	mi := &file_apci_users_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginLoginRequest) ProtoMessage() {}

func (x *BeginLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_users_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginLoginRequest.ProtoReflect.Descriptor instead.
func (*BeginLoginRequest) Descriptor() ([]byte, []int) {
	return file_apci_users_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *BeginLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BeginLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Challenge     []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginLoginResponse) Reset() {
	*x = BeginLoginResponse{}
	mi := &file_apci_users_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginLoginResponse) ProtoMessage() {}

func (x *BeginLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_users_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginLoginResponse.ProtoReflect.Descriptor instead.
func (*BeginLoginResponse) Descriptor() ([]byte, []int) {
	return file_apci_users_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *BeginLoginResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *BeginLoginResponse) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type CompleteLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ChallengeId   string                 `protobuf:"bytes,2,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	DeviceHash    string                 `protobuf:"bytes,4,opt,name=device_hash,json=deviceHash,proto3" json:"device_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteLoginRequest) Reset() {
	*x = CompleteLoginRequest{}
	mi := &file_apci_users_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLoginRequest) ProtoMessage() {}

func (x *CompleteLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_users_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLoginRequest.ProtoReflect.Descriptor instead.
func (*CompleteLoginRequest) Descriptor() ([]byte, []int) {
	return file_apci_users_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CompleteLoginRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteLoginRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CompleteLoginRequest) GetDeviceHash() string {
	if x != nil {
		return x.DeviceHash
	}
	return ""
}

type CompleteLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteLoginResponse) Reset() {
	*x = CompleteLoginResponse{}
	mi := &file_apci_users_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteLoginResponse) ProtoMessage() {}

func (x *CompleteLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_users_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteLoginResponse.ProtoReflect.Descriptor instead.
func (*CompleteLoginResponse) Descriptor() ([]byte, []int) {
	return file_apci_users_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteLoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteLoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteLoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_apci_users_v1_users_proto protoreflect.FileDescriptor

const file_apci_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x19apci/users/v1/users.proto\x12\rapci.users.v1\"|\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12,\n" +
	"\x12ed25519_public_key\x18\x02 \x01(\fR\x10ed25519PublicKey\x12\x1f\n" +
	"\vdevice_hash\x18\x03 \x01(\tR\n" +
	"deviceHash\"G\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"/\n" +
	"\x11BeginLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"U\n" +
	"\x12BeginLoginResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\"\x94\x01\n" +
	"\x14CompleteLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fchallenge_id\x18\x02 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1f\n" +
	"\vdevice_hash\x18\x04 \x01(\tR\n" +
	"deviceHash\"k\n" +
	"\x15CompleteLoginResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername2\x8a\x02\n" +
	"\fUsersService\x12K\n" +
	"\bRegister\x12\x1e.apci.users.v1.RegisterRequest\x1a\x1f.apci.users.v1.RegisterResponse\x12Q\n" +
	"\n" +
	"BeginLogin\x12 .apci.users.v1.BeginLoginRequest\x1a!.apci.users.v1.BeginLoginResponse\x12Z\n" +
	"\rCompleteLogin\x12#.apci.users.v1.CompleteLoginRequest\x1a$.apci.users.v1.CompleteLoginResponseB?Z=github.com/black/apci-app/server/pkg/pb/apci/users/v1;usersv1b\x06proto3"

var (
	file_apci_users_v1_users_proto_rawDescOnce sync.Once
	file_apci_users_v1_users_proto_rawDescData []byte
)

func file_apci_users_v1_users_proto_rawDescGZIP() []byte {
	file_apci_users_v1_users_proto_rawDescOnce.Do(func() {
		file_apci_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apci_users_v1_users_proto_rawDesc), len(file_apci_users_v1_users_proto_rawDesc)))
	})
	return file_apci_users_v1_users_proto_rawDescData
}

var file_apci_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apci_users_v1_users_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: apci.users.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: apci.users.v1.RegisterResponse
	(*BeginLoginRequest)(nil),     // 2: apci.users.v1.BeginLoginRequest
	(*BeginLoginResponse)(nil),    // 3: apci.users.v1.BeginLoginResponse
	(*CompleteLoginRequest)(nil),  // 4: apci.users.v1.CompleteLoginRequest
	(*CompleteLoginResponse)(nil), // 5: apci.users.v1.CompleteLoginResponse
}
var file_apci_users_v1_users_proto_depIdxs = []int32{
	0, // 0: apci.users.v1.UsersService.Register:input_type -> apci.users.v1.RegisterRequest
	2, // 1: apci.users.v1.UsersService.BeginLogin:input_type -> apci.users.v1.BeginLoginRequest
	4, // 2: apci.users.v1.UsersService.CompleteLogin:input_type -> apci.users.v1.CompleteLoginRequest
	1, // 3: apci.users.v1.UsersService.Register:output_type -> apci.users.v1.RegisterResponse
	3, // 4: apci.users.v1.UsersService.BeginLogin:output_type -> apci.users.v1.BeginLoginResponse
	5, // 5: apci.users.v1.UsersService.CompleteLogin:output_type -> apci.users.v1.CompleteLoginResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apci_users_v1_users_proto_init() }
func file_apci_users_v1_users_proto_init() {
	if File_apci_users_v1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apci_users_v1_users_proto_rawDesc), len(file_apci_users_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apci_users_v1_users_proto_goTypes,
		DependencyIndexes: file_apci_users_v1_users_proto_depIdxs,
		MessageInfos:      file_apci_users_v1_users_proto_msgTypes,
	}.Build()
	File_apci_users_v1_users_proto = out.File
	file_apci_users_v1_users_proto_goTypes = nil
	file_apci_users_v1_users_proto_depIdxs = nil
}
