// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: apci/security/v1/ingest.proto

package securityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityIngest_IngestEvent_FullMethodName = "/apci.security.v1.SecurityIngest/IngestEvent"
)

// SecurityIngestClient is the client API for SecurityIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecurityIngest receives async events from Chat API (fire-and-forget).
type SecurityIngestClient interface {
	IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error)
}

type securityIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityIngestClient(cc grpc.ClientConnInterface) SecurityIngestClient {
	return &securityIngestClient{cc}
}

func (c *securityIngestClient) IngestEvent(ctx context.Context, in *IngestEventRequest, opts ...grpc.CallOption) (*IngestEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestEventResponse)
	err := c.cc.Invoke(ctx, SecurityIngest_IngestEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityIngestServer is the server API for SecurityIngest service.
// All implementations must embed UnimplementedSecurityIngestServer
// for forward compatibility.
//
// SecurityIngest receives async events from Chat API (fire-and-forget).
type SecurityIngestServer interface {
	IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error)
	mustEmbedUnimplementedSecurityIngestServer()
}

// UnimplementedSecurityIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityIngestServer struct{}

func (UnimplementedSecurityIngestServer) IngestEvent(context.Context, *IngestEventRequest) (*IngestEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestEvent not implemented")
}
func (UnimplementedSecurityIngestServer) mustEmbedUnimplementedSecurityIngestServer() {}
func (UnimplementedSecurityIngestServer) testEmbeddedByValue()                        {}

// UnsafeSecurityIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityIngestServer will
// result in compilation errors.
type UnsafeSecurityIngestServer interface {
	mustEmbedUnimplementedSecurityIngestServer()
}

func RegisterSecurityIngestServer(s grpc.ServiceRegistrar, srv SecurityIngestServer) {
	// If the following call panics, it indicates UnimplementedSecurityIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityIngest_ServiceDesc, srv)
}

func _SecurityIngest_IngestEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityIngestServer).IngestEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityIngest_IngestEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityIngestServer).IngestEvent(ctx, req.(*IngestEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityIngest_ServiceDesc is the grpc.ServiceDesc for SecurityIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apci.security.v1.SecurityIngest",
	HandlerType: (*SecurityIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestEvent",
			Handler:    _SecurityIngest_IngestEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apci/security/v1/ingest.proto",
}
