// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: apci/security/v1/ingest.proto

package securityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestEventRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EventId    string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType  string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// user.registered / user.logged_in
	UserId     string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceHash string `protobuf:"bytes,5,opt,name=device_hash,json=deviceHash,proto3" json:"device_hash,omitempty"`
	// contact.added
	ContactId string `protobuf:"bytes,7,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	// message.sent
	PeerUserId    string `protobuf:"bytes,8,opt,name=peer_user_id,json=peerUserId,proto3" json:"peer_user_id,omitempty"`
	MessageId     string `protobuf:"bytes,9,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_apci_security_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_security_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_apci_security_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IngestEventRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *IngestEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IngestEventRequest) GetDeviceHash() string {
	if x != nil {
		return x.DeviceHash
	}
	return ""
}

func (x *IngestEventRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *IngestEventRequest) GetPeerUserId() string {
	if x != nil {
		return x.PeerUserId
	}
	return ""
}

func (x *IngestEventRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type IngestEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Duplicate     bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_apci_security_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_security_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_apci_security_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestEventResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

var File_apci_security_v1_ingest_proto protoreflect.FileDescriptor

const file_apci_security_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1dapci/security/v1/ingest.proto\x12\x10apci.security.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\x12IngestEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdevice_hash\x18\x05 \x01(\tR\n" +
	"deviceHash\x12\x1d\n" +
	"\n" +
	"contact_id\x18\a \x01(\tR\tcontactId\x12 \n" +
	"\fpeer_user_id\x18\b \x01(\tR\n" +
	"peerUserId\x12\x1d\n" +
	"\n" +
	"message_id\x18\t \x01(\tR\tmessageIdJ\x04\b\x06\x10\aR\aip_hash\"O\n" +
	"\x13IngestEventResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate2l\n" +
	"\x0eSecurityIngest\x12Z\n" +
	"\vIngestEvent\x12$.apci.security.v1.IngestEventRequest\x1a%.apci.security.v1.IngestEventResponseBNZLgithub.com/black/apci-app/security-center/pkg/pb/apci/security/v1;securityv1b\x06proto3"

var (
	file_apci_security_v1_ingest_proto_rawDescOnce sync.Once
	file_apci_security_v1_ingest_proto_rawDescData []byte
)

func file_apci_security_v1_ingest_proto_rawDescGZIP() []byte {
	file_apci_security_v1_ingest_proto_rawDescOnce.Do(func() {
		file_apci_security_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apci_security_v1_ingest_proto_rawDesc), len(file_apci_security_v1_ingest_proto_rawDesc)))
	})
	return file_apci_security_v1_ingest_proto_rawDescData
}

var file_apci_security_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apci_security_v1_ingest_proto_goTypes = []any{
	(*IngestEventRequest)(nil),    // 0: apci.security.v1.IngestEventRequest
	(*IngestEventResponse)(nil),   // 1: apci.security.v1.IngestEventResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_apci_security_v1_ingest_proto_depIdxs = []int32{
	2, // 0: apci.security.v1.IngestEventRequest.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 1: apci.security.v1.SecurityIngest.IngestEvent:input_type -> apci.security.v1.IngestEventRequest
	1, // 2: apci.security.v1.SecurityIngest.IngestEvent:output_type -> apci.security.v1.IngestEventResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apci_security_v1_ingest_proto_init() }
func file_apci_security_v1_ingest_proto_init() {
	if File_apci_security_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apci_security_v1_ingest_proto_rawDesc), len(file_apci_security_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apci_security_v1_ingest_proto_goTypes,
		DependencyIndexes: file_apci_security_v1_ingest_proto_depIdxs,
		MessageInfos:      file_apci_security_v1_ingest_proto_msgTypes,
	}.Build()
	File_apci_security_v1_ingest_proto = out.File
	file_apci_security_v1_ingest_proto_goTypes = nil
	file_apci_security_v1_ingest_proto_depIdxs = nil
}
