// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CurrentUser():Promise<main.AuthResult>;

export function Login(arg1:string):Promise<main.AuthResult>;

export function Logout():Promise<void>;

export function Register(arg1:string):Promise<main.AuthResult>;
