// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentUser() {
  return window['go']['main']['App']['CurrentUser']();
}

export function E2EInbox(arg1, arg2) {
  return window['go']['main']['App']['E2EInbox'](arg1, arg2);
}

export function E2EInit() {
  return window['go']['main']['App']['E2EInit']();
}

export function E2ESend(arg1, arg2, arg3) {
  return window['go']['main']['App']['E2ESend'](arg1, arg2, arg3);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function SetFingerprintSignals(arg1) {
  return window['go']['main']['App']['SetFingerprintSignals'](arg1);
}
