// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apci/e2e/v1/e2e.proto

package e2ev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedPreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         uint32                 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // X25519, 32 байта
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                  // подпись identity key
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedPreKey) Reset() {
	*x = SignedPreKey{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedPreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedPreKey) ProtoMessage() {}

func (x *SignedPreKey) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedPreKey.ProtoReflect.Descriptor instead.
func (*SignedPreKey) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{0}
}

func (x *SignedPreKey) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *SignedPreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *SignedPreKey) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedPreKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type OneTimePreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         uint32                 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // X25519, 32 байта
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneTimePreKey) Reset() {
	*x = OneTimePreKey{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneTimePreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneTimePreKey) ProtoMessage() {}

func (x *OneTimePreKey) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneTimePreKey.ProtoReflect.Descriptor instead.
func (*OneTimePreKey) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{1}
}

func (x *OneTimePreKey) GetKeyId() uint32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *OneTimePreKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type UploadPreKeyBundleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey    []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"` // X25519 identity public key (не Ed25519 ключ auth)
	SignedPrekey   *SignedPreKey          `protobuf:"bytes,2,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`
	OneTimePrekeys []*OneTimePreKey       `protobuf:"bytes,3,rep,name=one_time_prekeys,json=oneTimePrekeys,proto3" json:"one_time_prekeys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadPreKeyBundleRequest) Reset() {
	*x = UploadPreKeyBundleRequest{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPreKeyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPreKeyBundleRequest) ProtoMessage() {}

func (x *UploadPreKeyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPreKeyBundleRequest.ProtoReflect.Descriptor instead.
func (*UploadPreKeyBundleRequest) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{2}
}

func (x *UploadPreKeyBundleRequest) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *UploadPreKeyBundleRequest) GetSignedPrekey() *SignedPreKey {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *UploadPreKeyBundleRequest) GetOneTimePrekeys() []*OneTimePreKey {
	if x != nil {
		return x.OneTimePrekeys
	}
	return nil
}

type UploadPreKeyBundleResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OneTimePrekeysAccepted uint32                 `protobuf:"varint,1,opt,name=one_time_prekeys_accepted,json=oneTimePrekeysAccepted,proto3" json:"one_time_prekeys_accepted,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UploadPreKeyBundleResponse) Reset() {
	*x = UploadPreKeyBundleResponse{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPreKeyBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPreKeyBundleResponse) ProtoMessage() {}

func (x *UploadPreKeyBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPreKeyBundleResponse.ProtoReflect.Descriptor instead.
func (*UploadPreKeyBundleResponse) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{3}
}

func (x *UploadPreKeyBundleResponse) GetOneTimePrekeysAccepted() uint32 {
	if x != nil {
		return x.OneTimePrekeysAccepted
	}
	return 0
}

type GetPreKeyBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreKeyBundleRequest) Reset() {
	*x = GetPreKeyBundleRequest{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreKeyBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreKeyBundleRequest) ProtoMessage() {}

func (x *GetPreKeyBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreKeyBundleRequest.ProtoReflect.Descriptor instead.
func (*GetPreKeyBundleRequest) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{4}
}

func (x *GetPreKeyBundleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPreKeyBundleResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdentityKey           []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SignedPrekeyId        uint32                 `protobuf:"varint,3,opt,name=signed_prekey_id,json=signedPrekeyId,proto3" json:"signed_prekey_id,omitempty"`
	SignedPrekey          []byte                 `protobuf:"bytes,4,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`
	SignedPrekeySignature []byte                 `protobuf:"bytes,5,opt,name=signed_prekey_signature,json=signedPrekeySignature,proto3" json:"signed_prekey_signature,omitempty"`
	OneTimePrekeyId       uint32                 `protobuf:"varint,6,opt,name=one_time_prekey_id,json=oneTimePrekeyId,proto3" json:"one_time_prekey_id,omitempty"` // 0, если one-time prekey недоступен
	OneTimePrekey         []byte                 `protobuf:"bytes,7,opt,name=one_time_prekey,json=oneTimePrekey,proto3" json:"one_time_prekey,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetPreKeyBundleResponse) Reset() {
	*x = GetPreKeyBundleResponse{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreKeyBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreKeyBundleResponse) ProtoMessage() {}

func (x *GetPreKeyBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreKeyBundleResponse.ProtoReflect.Descriptor instead.
func (*GetPreKeyBundleResponse) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{5}
}

func (x *GetPreKeyBundleResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPreKeyBundleResponse) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *GetPreKeyBundleResponse) GetSignedPrekeyId() uint32 {
	if x != nil {
		return x.SignedPrekeyId
	}
	return 0
}

func (x *GetPreKeyBundleResponse) GetSignedPrekey() []byte {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *GetPreKeyBundleResponse) GetSignedPrekeySignature() []byte {
	if x != nil {
		return x.SignedPrekeySignature
	}
	return nil
}

func (x *GetPreKeyBundleResponse) GetOneTimePrekeyId() uint32 {
	if x != nil {
		return x.OneTimePrekeyId
	}
	return 0
}

func (x *GetPreKeyBundleResponse) GetOneTimePrekey() []byte {
	if x != nil {
		return x.OneTimePrekey
	}
	return nil
}

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecipientId      string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	ChatId           string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	RatchetSessionId string                 `protobuf:"bytes,3,opt,name=ratchet_session_id,json=ratchetSessionId,proto3" json:"ratchet_session_id,omitempty"`
	Ciphertext       []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	RatchetHeader    []byte                 `protobuf:"bytes,5,opt,name=ratchet_header,json=ratchetHeader,proto3" json:"ratchet_header,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetRatchetSessionId() string {
	if x != nil {
		return x.RatchetSessionId
	}
	return ""
}

func (x *SendMessageRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SendMessageRequest) GetRatchetHeader() []byte {
	if x != nil {
		return x.RatchetHeader
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type FetchMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Сообщения после этого id (не включая его). Пусто — с начала.
	SinceMessageId string `protobuf:"bytes,1,opt,name=since_message_id,json=sinceMessageId,proto3" json:"since_message_id,omitempty"`
	Limit          uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // на сервере по умолчанию 50, если 0
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchMessagesRequest) Reset() {
	*x = FetchMessagesRequest{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessagesRequest) ProtoMessage() {}

func (x *FetchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessagesRequest.ProtoReflect.Descriptor instead.
func (*FetchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{8}
}

func (x *FetchMessagesRequest) GetSinceMessageId() string {
	if x != nil {
		return x.SinceMessageId
	}
	return ""
}

func (x *FetchMessagesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FetchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*EncryptedMessage    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMessagesResponse) Reset() {
	*x = FetchMessagesResponse{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMessagesResponse) ProtoMessage() {}

func (x *FetchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMessagesResponse.ProtoReflect.Descriptor instead.
func (*FetchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{9}
}

func (x *FetchMessagesResponse) GetMessages() []*EncryptedMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type EncryptedMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId           string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	RatchetSessionId string                 `protobuf:"bytes,3,opt,name=ratchet_session_id,json=ratchetSessionId,proto3" json:"ratchet_session_id,omitempty"`
	SenderId         string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId      string                 `protobuf:"bytes,5,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Ciphertext       []byte                 `protobuf:"bytes,6,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	RatchetHeader    []byte                 `protobuf:"bytes,7,opt,name=ratchet_header,json=ratchetHeader,proto3" json:"ratchet_header,omitempty"`
	SentAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apci_e2e_v1_e2e_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_apci_e2e_v1_e2e_proto_rawDescGZIP(), []int{10}
}

func (x *EncryptedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EncryptedMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *EncryptedMessage) GetRatchetSessionId() string {
	if x != nil {
		return x.RatchetSessionId
	}
	return ""
}

func (x *EncryptedMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EncryptedMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *EncryptedMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedMessage) GetRatchetHeader() []byte {
	if x != nil {
		return x.RatchetHeader
	}
	return nil
}

func (x *EncryptedMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_apci_e2e_v1_e2e_proto protoreflect.FileDescriptor

const file_apci_e2e_v1_e2e_proto_rawDesc = "" +
	"\n" +
	"\x15apci/e2e/v1/e2e.proto\x12\vapci.e2e.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\fSignedPreKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\rR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"E\n" +
	"\rOneTimePreKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\rR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xc4\x01\n" +
	"\x19UploadPreKeyBundleRequest\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12>\n" +
	"\rsigned_prekey\x18\x02 \x01(\v2\x19.apci.e2e.v1.SignedPreKeyR\fsignedPrekey\x12D\n" +
	"\x10one_time_prekeys\x18\x03 \x03(\v2\x1a.apci.e2e.v1.OneTimePreKeyR\x0eoneTimePrekeys\"W\n" +
	"\x1aUploadPreKeyBundleResponse\x129\n" +
	"\x19one_time_prekeys_accepted\x18\x01 \x01(\rR\x16oneTimePrekeysAccepted\"1\n" +
	"\x16GetPreKeyBundleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb1\x02\n" +
	"\x17GetPreKeyBundleResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12(\n" +
	"\x10signed_prekey_id\x18\x03 \x01(\rR\x0esignedPrekeyId\x12#\n" +
	"\rsigned_prekey\x18\x04 \x01(\fR\fsignedPrekey\x126\n" +
	"\x17signed_prekey_signature\x18\x05 \x01(\fR\x15signedPrekeySignature\x12+\n" +
	"\x12one_time_prekey_id\x18\x06 \x01(\rR\x0foneTimePrekeyId\x12&\n" +
	"\x0fone_time_prekey\x18\a \x01(\fR\roneTimePrekey\"\xc5\x01\n" +
	"\x12SendMessageRequest\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12,\n" +
	"\x12ratchet_session_id\x18\x03 \x01(\tR\x10ratchetSessionId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12%\n" +
	"\x0eratchet_header\x18\x05 \x01(\fR\rratchetHeader\"i\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"V\n" +
	"\x14FetchMessagesRequest\x12(\n" +
	"\x10since_message_id\x18\x01 \x01(\tR\x0esinceMessageId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"R\n" +
	"\x15FetchMessagesResponse\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.apci.e2e.v1.EncryptedMessageR\bmessages\"\xb4\x02\n" +
	"\x10EncryptedMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12,\n" +
	"\x12ratchet_session_id\x18\x03 \x01(\tR\x10ratchetSessionId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x05 \x01(\tR\vrecipientId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x06 \x01(\fR\n" +
	"ciphertext\x12%\n" +
	"\x0eratchet_header\x18\a \x01(\fR\rratchetHeader\x123\n" +
	"\asent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt2\xfb\x02\n" +
	"\n" +
	"E2EService\x12e\n" +
	"\x12UploadPreKeyBundle\x12&.apci.e2e.v1.UploadPreKeyBundleRequest\x1a'.apci.e2e.v1.UploadPreKeyBundleResponse\x12\\\n" +
	"\x0fGetPreKeyBundle\x12#.apci.e2e.v1.GetPreKeyBundleRequest\x1a$.apci.e2e.v1.GetPreKeyBundleResponse\x12P\n" +
	"\vSendMessage\x12\x1f.apci.e2e.v1.SendMessageRequest\x1a .apci.e2e.v1.SendMessageResponse\x12V\n" +
	"\rFetchMessages\x12!.apci.e2e.v1.FetchMessagesRequest\x1a\".apci.e2e.v1.FetchMessagesResponseB;Z9github.com/black/apci-app/server/pkg/pb/apci/e2e/v1;e2ev1b\x06proto3"

var (
	file_apci_e2e_v1_e2e_proto_rawDescOnce sync.Once
	file_apci_e2e_v1_e2e_proto_rawDescData []byte
)

func file_apci_e2e_v1_e2e_proto_rawDescGZIP() []byte {
	file_apci_e2e_v1_e2e_proto_rawDescOnce.Do(func() {
		file_apci_e2e_v1_e2e_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apci_e2e_v1_e2e_proto_rawDesc), len(file_apci_e2e_v1_e2e_proto_rawDesc)))
	})
	return file_apci_e2e_v1_e2e_proto_rawDescData
}

var file_apci_e2e_v1_e2e_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apci_e2e_v1_e2e_proto_goTypes = []any{
	(*SignedPreKey)(nil),               // 0: apci.e2e.v1.SignedPreKey
	(*OneTimePreKey)(nil),              // 1: apci.e2e.v1.OneTimePreKey
	(*UploadPreKeyBundleRequest)(nil),  // 2: apci.e2e.v1.UploadPreKeyBundleRequest
	(*UploadPreKeyBundleResponse)(nil), // 3: apci.e2e.v1.UploadPreKeyBundleResponse
	(*GetPreKeyBundleRequest)(nil),     // 4: apci.e2e.v1.GetPreKeyBundleRequest
	(*GetPreKeyBundleResponse)(nil),    // 5: apci.e2e.v1.GetPreKeyBundleResponse
	(*SendMessageRequest)(nil),         // 6: apci.e2e.v1.SendMessageRequest
	(*SendMessageResponse)(nil),        // 7: apci.e2e.v1.SendMessageResponse
	(*FetchMessagesRequest)(nil),       // 8: apci.e2e.v1.FetchMessagesRequest
	(*FetchMessagesResponse)(nil),      // 9: apci.e2e.v1.FetchMessagesResponse
	(*EncryptedMessage)(nil),           // 10: apci.e2e.v1.EncryptedMessage
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_apci_e2e_v1_e2e_proto_depIdxs = []int32{
	11, // 0: apci.e2e.v1.SignedPreKey.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 1: apci.e2e.v1.UploadPreKeyBundleRequest.signed_prekey:type_name -> apci.e2e.v1.SignedPreKey
	1,  // 2: apci.e2e.v1.UploadPreKeyBundleRequest.one_time_prekeys:type_name -> apci.e2e.v1.OneTimePreKey
	11, // 3: apci.e2e.v1.SendMessageResponse.sent_at:type_name -> google.protobuf.Timestamp
	10, // 4: apci.e2e.v1.FetchMessagesResponse.messages:type_name -> apci.e2e.v1.EncryptedMessage
	11, // 5: apci.e2e.v1.EncryptedMessage.sent_at:type_name -> google.protobuf.Timestamp
	2,  // 6: apci.e2e.v1.E2EService.UploadPreKeyBundle:input_type -> apci.e2e.v1.UploadPreKeyBundleRequest
	4,  // 7: apci.e2e.v1.E2EService.GetPreKeyBundle:input_type -> apci.e2e.v1.GetPreKeyBundleRequest
	6,  // 8: apci.e2e.v1.E2EService.SendMessage:input_type -> apci.e2e.v1.SendMessageRequest
	8,  // 9: apci.e2e.v1.E2EService.FetchMessages:input_type -> apci.e2e.v1.FetchMessagesRequest
	3,  // 10: apci.e2e.v1.E2EService.UploadPreKeyBundle:output_type -> apci.e2e.v1.UploadPreKeyBundleResponse
	5,  // 11: apci.e2e.v1.E2EService.GetPreKeyBundle:output_type -> apci.e2e.v1.GetPreKeyBundleResponse
	7,  // 12: apci.e2e.v1.E2EService.SendMessage:output_type -> apci.e2e.v1.SendMessageResponse
	9,  // 13: apci.e2e.v1.E2EService.FetchMessages:output_type -> apci.e2e.v1.FetchMessagesResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_apci_e2e_v1_e2e_proto_init() }
func file_apci_e2e_v1_e2e_proto_init() {
	if File_apci_e2e_v1_e2e_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apci_e2e_v1_e2e_proto_rawDesc), len(file_apci_e2e_v1_e2e_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apci_e2e_v1_e2e_proto_goTypes,
		DependencyIndexes: file_apci_e2e_v1_e2e_proto_depIdxs,
		MessageInfos:      file_apci_e2e_v1_e2e_proto_msgTypes,
	}.Build()
	File_apci_e2e_v1_e2e_proto = out.File
	file_apci_e2e_v1_e2e_proto_goTypes = nil
	file_apci_e2e_v1_e2e_proto_depIdxs = nil
}
