// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: apci/e2e/v1/e2e.proto

package e2ev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	E2EService_UploadPreKeyBundle_FullMethodName = "/apci.e2e.v1.E2EService/UploadPreKeyBundle"
	E2EService_GetPreKeyBundle_FullMethodName    = "/apci.e2e.v1.E2EService/GetPreKeyBundle"
	E2EService_SendMessage_FullMethodName        = "/apci.e2e.v1.E2EService/SendMessage"
	E2EService_FetchMessages_FullMethodName      = "/apci.e2e.v1.E2EService/FetchMessages"
)

// E2EServiceClient is the client API for E2EService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// E2E: relay сообщений и хранение public prekeys.
//
// Auth (все RPC): gRPC metadata "session-id" — сессия входа из
// UsersService.CompleteLogin. Не путать с ratchet_session_id в теле запроса.
//
// chat_id: создаётся модулем chats; e2e только ссылается на него в сообщениях.
//
// ratchet_session_id: id crypto-сессии Double Ratchet (генерируется на клиенте).
type E2EServiceClient interface {
	// Загрузка X25519 prekey bundle после входа. Заменяет предыдущий bundle пользователя.
	UploadPreKeyBundle(ctx context.Context, in *UploadPreKeyBundleRequest, opts ...grpc.CallOption) (*UploadPreKeyBundleResponse, error)
	// Получение prekey bundle другого пользователя для X3DH на клиенте.
	GetPreKeyBundle(ctx context.Context, in *GetPreKeyBundleRequest, opts ...grpc.CallOption) (*GetPreKeyBundleResponse, error)
	// Отправка зашифрованного сообщения. Открытый текст только на клиенте.
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	// Опрос входящих сообщений (MVP). Потоковая доставка — в roadmap.
	FetchMessages(ctx context.Context, in *FetchMessagesRequest, opts ...grpc.CallOption) (*FetchMessagesResponse, error)
}

type e2EServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewE2EServiceClient(cc grpc.ClientConnInterface) E2EServiceClient {
	return &e2EServiceClient{cc}
}

func (c *e2EServiceClient) UploadPreKeyBundle(ctx context.Context, in *UploadPreKeyBundleRequest, opts ...grpc.CallOption) (*UploadPreKeyBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPreKeyBundleResponse)
	err := c.cc.Invoke(ctx, E2EService_UploadPreKeyBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2EServiceClient) GetPreKeyBundle(ctx context.Context, in *GetPreKeyBundleRequest, opts ...grpc.CallOption) (*GetPreKeyBundleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPreKeyBundleResponse)
	err := c.cc.Invoke(ctx, E2EService_GetPreKeyBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2EServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, E2EService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *e2EServiceClient) FetchMessages(ctx context.Context, in *FetchMessagesRequest, opts ...grpc.CallOption) (*FetchMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchMessagesResponse)
	err := c.cc.Invoke(ctx, E2EService_FetchMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// E2EServiceServer is the server API for E2EService service.
// All implementations must embed UnimplementedE2EServiceServer
// for forward compatibility.
//
// E2E: relay сообщений и хранение public prekeys.
//
// Auth (все RPC): gRPC metadata "session-id" — сессия входа из
// UsersService.CompleteLogin. Не путать с ratchet_session_id в теле запроса.
//
// chat_id: создаётся модулем chats; e2e только ссылается на него в сообщениях.
//
// ratchet_session_id: id crypto-сессии Double Ratchet (генерируется на клиенте).
type E2EServiceServer interface {
	// Загрузка X25519 prekey bundle после входа. Заменяет предыдущий bundle пользователя.
	UploadPreKeyBundle(context.Context, *UploadPreKeyBundleRequest) (*UploadPreKeyBundleResponse, error)
	// Получение prekey bundle другого пользователя для X3DH на клиенте.
	GetPreKeyBundle(context.Context, *GetPreKeyBundleRequest) (*GetPreKeyBundleResponse, error)
	// Отправка зашифрованного сообщения. Открытый текст только на клиенте.
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	// Опрос входящих сообщений (MVP). Потоковая доставка — в roadmap.
	FetchMessages(context.Context, *FetchMessagesRequest) (*FetchMessagesResponse, error)
	mustEmbedUnimplementedE2EServiceServer()
}

// UnimplementedE2EServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedE2EServiceServer struct{}

func (UnimplementedE2EServiceServer) UploadPreKeyBundle(context.Context, *UploadPreKeyBundleRequest) (*UploadPreKeyBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPreKeyBundle not implemented")
}
func (UnimplementedE2EServiceServer) GetPreKeyBundle(context.Context, *GetPreKeyBundleRequest) (*GetPreKeyBundleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreKeyBundle not implemented")
}
func (UnimplementedE2EServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedE2EServiceServer) FetchMessages(context.Context, *FetchMessagesRequest) (*FetchMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchMessages not implemented")
}
func (UnimplementedE2EServiceServer) mustEmbedUnimplementedE2EServiceServer() {}
func (UnimplementedE2EServiceServer) testEmbeddedByValue()                    {}

// UnsafeE2EServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to E2EServiceServer will
// result in compilation errors.
type UnsafeE2EServiceServer interface {
	mustEmbedUnimplementedE2EServiceServer()
}

func RegisterE2EServiceServer(s grpc.ServiceRegistrar, srv E2EServiceServer) {
	// If the following call panics, it indicates UnimplementedE2EServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&E2EService_ServiceDesc, srv)
}

func _E2EService_UploadPreKeyBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPreKeyBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2EServiceServer).UploadPreKeyBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2EService_UploadPreKeyBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2EServiceServer).UploadPreKeyBundle(ctx, req.(*UploadPreKeyBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2EService_GetPreKeyBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreKeyBundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2EServiceServer).GetPreKeyBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2EService_GetPreKeyBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2EServiceServer).GetPreKeyBundle(ctx, req.(*GetPreKeyBundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2EService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2EServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2EService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2EServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _E2EService_FetchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(E2EServiceServer).FetchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: E2EService_FetchMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(E2EServiceServer).FetchMessages(ctx, req.(*FetchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// E2EService_ServiceDesc is the grpc.ServiceDesc for E2EService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var E2EService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apci.e2e.v1.E2EService",
	HandlerType: (*E2EServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadPreKeyBundle",
			Handler:    _E2EService_UploadPreKeyBundle_Handler,
		},
		{
			MethodName: "GetPreKeyBundle",
			Handler:    _E2EService_GetPreKeyBundle_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _E2EService_SendMessage_Handler,
		},
		{
			MethodName: "FetchMessages",
			Handler:    _E2EService_FetchMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apci/e2e/v1/e2e.proto",
}
